Add browser mode for Kepler Companion
kuzzleio/kepler pull request #2
Opened 2022-02-10 16:40 UTC by alexandrebouthinon

# Why?
We need to send analytics from Node.js apps (like Kourou) AND Web app (like the Admin Console)

# How?
- Implements the `browser` mode unique identifier generation:
  - It get the `kepler-user-id` from the localStorage
  - Generate a new one et store it in localStorage if it do not exist
  - Hash it  and send it to the Kepler Server
- Use `axios` instead of `node-fetch` to send HTTP POST request since it is ES6 and browser compatible.

2022-02-11 09:45 UTC, Aschen requested changes

2022-02-11 09:45 UTC, Aschen commented on kepler-companion/package.json
> +    "axios": "^0.25.0"
Why are you adding another dependency since you could use Kuzzle SDK to send analytics to Kepler? We should be careful about dependencies and only add them when it's necessary, especially when creating a library that will be embedded in other applications

2022-02-11 09:45 UTC, Aschen commented on kepler-companion/index.ts
>  import getMAC from 'getmac';
Files containing class name should be named according to the class, here `KeplerCompanion.ts`

2022-02-11 09:45 UTC, Aschen commented on kepler-companion/index.ts
> +    mode: 'node',
The mode should be detected automatically like we are doing in the JS SDK

2022-02-11 09:45 UTC, Aschen commented on kepler-companion/index.ts
>    public get server_url() {
Function name should be camelCase

2022-02-11 09:45 UTC, Aschen commented on kepler-companion/index.ts
> +          identifier = crypto.randomBytes(16).toString('hex');
I'm not sure the `crypto` library is available in the browser

2022-02-11 09:45 UTC, Aschen commented on kepler-companion/index.ts
> +        if (typeof window === 'undefined') {
```suggestion
        if (window === undefined) {
```

2022-02-11 14:18 UTC, Aschen commented on kepler-companion/index.ts
> +          console.log('Kepler: generating user id');
Remaining console.log

2022-02-11 14:20 UTC, Aschen requested changes

2022-02-11 14:20 UTC, Aschen commented on kepler-companion/index.ts
> +          console.log('Kepler: generating user id');
Remaining console.log

2022-02-11 14:20 UTC, Aschen commented on kepler/lib/controllers/AnalyticsController.ts
> +      user: crypto.createHash('sha256').update(user).digest('hex'),
It's better to send a obfuscated data to Kuzzle than obfuscating it after (from a client point of view)

2022-02-15 09:21 UTC, alexandrebouthinon commented on kepler-companion/KeplerCompanion.ts
> +function generateUniqueIdForBrowser(): string {
@Aschen this is the function I use to generate random ID in a browser context

2022-02-15 14:05 UTC, alexandrebouthinon commented
Need to make the lib usable in a browser context (using WebPack or something else....)

2022-02-15 16:09 UTC, Aschen requested changes
Few more remarks.

2022-02-15 16:09 UTC, Aschen commented on kepler-companion/KeplerCompanion.ts
> +      }),
Should be replaced by (also, you are not awaiting the promise)
```suggestion
      innerTrack(opts).catch(() => {});
```

2022-02-15 16:09 UTC, Aschen commented on kepler/lib/controllers/AnalyticsController.ts
> +      console.log(response)
Debug leftover

2022-02-15 16:09 UTC, Aschen commented on kepler/lib/controllers/AnalyticsController.ts
> +        throw new Error(response.statusText);
This should be an `ExternalServiceError`

2022-02-15 16:09 UTC, Aschen commented on kepler/lib/controllers/AnalyticsController.ts
> +      user: crypto.createHash('sha256').update(user).digest('hex'),
:+1:

2022-02-15 16:09 UTC, Aschen commented on kepler/lib/controllers/AnalyticsController.ts
> +      const country = await Promise.race([
You don't need this kind of tricks on the server side since everything is handled asynchronously. Awaiting a promise here won't stop the other request from being processed.

In the client it's useful to not delay the end of the program but here the program is always running either way

2022-02-15 16:09 UTC, Aschen commented on kepler/lib/controllers/AnalyticsController.ts
> +        trackingPayload.tags = { ...trackingPayload.tags, country }
Do we have a mappings on the `country` field?

2022-02-15 17:49 UTC, Aschen approved these changes

2022-02-15 17:49 UTC, Aschen commented on kepler-companion/KeplerCompanion.ts
> +      }),
Few remarks here:
 -  you don't need the bound `innerTrack`
 - you don't need an additional promise
```suggestion
    return Promise.race([
      this._track(opts).catch(() => { /* Analytics should not interfer with user process */ }),
```

2022-02-15 20:01 UTC, Aschen requested changes

2022-02-15 20:01 UTC, Aschen commented on kepler-companion/KeplerCompanion.ts
> +        id = getMAC();
As said previously, it's better to send a hash of the MAC rather than the actual MAC so our users can be sure that we are not saving real mac addresses

2022-02-15 20:37 UTC, alexandrebouthinon commented on kepler-companion/KeplerCompanion.ts
> +        id = getMAC();
It was converted to draft to make some tests while you reviewed it, sorry 😓

2022-02-15 20:40 UTC, alexandrebouthinon commented
The Companion works just fine in both Node.js and browser context 🎉 
Next step Admin Console integration

2022-02-17 09:37 UTC, merged